/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Logica.DtFecha;
import javax.swing.JOptionPane;
import Logica.ISistema;
import Logica.SistemaFactory;
import Logica.Sistema;
import Logica.DtUsuario;
import Logica.DtEspectador;
import Logica.DtArtista;
 
/**
 *
 * @author User
 */
public class main extends javax.swing.JFrame {

    private ISistema sis;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    
        //Inicialización
        SistemaFactory fabrica = SistemaFactory.getInstance();
        sis = fabrica.getISistema();
        
        this.FrameAltaUsuario.setVisible(false);
        this.FrameConsultarUsuario.setVisible(false);
        this.FrameModificarUsuario.setVisible(false);
       
        //
        GroupTipoUsuario.add(EspectadorButton);
        GroupTipoUsuario.add(ArtistaButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTipoUsuario = new javax.swing.ButtonGroup();
        FrameAltaUsuario = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        EspectadorButton = new javax.swing.JRadioButton();
        ArtistaButton = new javax.swing.JRadioButton();
        LabelNickname = new javax.swing.JLabel();
        FieldNickname = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        LabelApellido = new javax.swing.JLabel();
        FieldApellido = new javax.swing.JTextField();
        LabelEmail = new javax.swing.JLabel();
        FieldEmail = new javax.swing.JTextField();
        LabelFecha_Nac = new javax.swing.JLabel();
        LabelDescripcion = new javax.swing.JLabel();
        FieldDescripcion = new javax.swing.JTextField();
        LabelBiografia = new javax.swing.JLabel();
        FieldBiografia = new javax.swing.JTextField();
        ButtonCancelar = new javax.swing.JButton();
        ButtonConfirmar = new javax.swing.JButton();
        LabelSitioWeb = new javax.swing.JLabel();
        FieldSitioWeb = new javax.swing.JTextField();
        ComboBoxDia = new javax.swing.JComboBox<>();
        ComboBoxMes = new javax.swing.JComboBox<>();
        ComboBoxAnio = new javax.swing.JComboBox<>();
        LabelDia = new javax.swing.JLabel();
        LabelAnio = new javax.swing.JLabel();
        LabelMes = new javax.swing.JLabel();
        FrameConsultarUsuario = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaRegistro2 = new javax.swing.JList<>();
        LabelNickname2 = new javax.swing.JLabel();
        FieldNickname2 = new javax.swing.JTextField();
        LabelNombre2 = new javax.swing.JLabel();
        FieldNombre2 = new javax.swing.JTextField();
        LabelApellido2 = new javax.swing.JLabel();
        FieldApellido2 = new javax.swing.JTextField();
        LabelCorreo2 = new javax.swing.JLabel();
        FieldCorreo2 = new javax.swing.JTextField();
        LabelFechaNac2 = new javax.swing.JLabel();
        FieldFechaNac2 = new javax.swing.JTextField();
        LabelDescripcion2 = new javax.swing.JLabel();
        FieldDescripcion2 = new javax.swing.JTextField();
        LabelBiografia2 = new javax.swing.JLabel();
        FieldBiografia2 = new javax.swing.JTextField();
        LabelLink2 = new javax.swing.JLabel();
        FieldLink2 = new javax.swing.JTextField();
        LabelNickname3 = new javax.swing.JLabel();
        LabelEspectaculosOrganizo2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaUsuarios2 = new javax.swing.JList<>();
        LabelEspectaculosRegistro2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaOrganizo2 = new javax.swing.JList<>();
        BotonSalir2 = new javax.swing.JButton();
        FrameModificarUsuario = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaUsuarios3 = new javax.swing.JList<>();
        LabelSeleccionarUsuario3 = new javax.swing.JLabel();
        LabelLink3 = new javax.swing.JLabel();
        LabelApellido3 = new javax.swing.JLabel();
        LabelFechaNac3 = new javax.swing.JLabel();
        FieldBiografia3 = new javax.swing.JTextField();
        FieldApellido3 = new javax.swing.JTextField();
        FieldLink3 = new javax.swing.JTextField();
        FieldDescripcion3 = new javax.swing.JTextField();
        LabelDescripcion3 = new javax.swing.JLabel();
        LabelBiografia3 = new javax.swing.JLabel();
        LabelNombre3 = new javax.swing.JLabel();
        FieldNombre3 = new javax.swing.JTextField();
        BotonCancelar3 = new javax.swing.JButton();
        LabelDia3 = new javax.swing.JLabel();
        LabelMes3 = new javax.swing.JLabel();
        LabelAnio3 = new javax.swing.JLabel();
        ComboBoxDia3 = new javax.swing.JComboBox<>();
        ComboBoxMes3 = new javax.swing.JComboBox<>();
        ComboBoxAnio3 = new javax.swing.JComboBox<>();
        BotonConfirmar4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        AltaUsuario = new javax.swing.JMenuItem();
        ConsultaUsuario = new javax.swing.JMenuItem();
        ModificarUsuario = new javax.swing.JMenuItem();
        RegistroFuncionUsuario = new javax.swing.JMenuItem();
        menuEspectaculo = new javax.swing.JMenu();
        AltaEspectaculo = new javax.swing.JMenuItem();
        ConsultaEspectaculo = new javax.swing.JMenuItem();
        menuFuncion = new javax.swing.JMenu();
        AltaFuncion = new javax.swing.JMenuItem();
        ConsultaFuncion = new javax.swing.JMenuItem();
        menuPaquete = new javax.swing.JMenu();
        CrearPaquete = new javax.swing.JMenuItem();
        AgregarEspaPaq = new javax.swing.JMenuItem();
        ConsultaPaquete = new javax.swing.JMenuItem();
        menuPlataforma = new javax.swing.JMenu();
        AltaPlataforma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FrameAltaUsuario.setTitle("Alta de Usuario");
        FrameAltaUsuario.setMinimumSize(new java.awt.Dimension(500, 500));
        FrameAltaUsuario.setName(""); // NOI18N
        FrameAltaUsuario.setVisible(true);
        FrameAltaUsuario.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Indique si el usuario a ingresar es Espectador o Artista");
        FrameAltaUsuario.getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 390, 22);

        EspectadorButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EspectadorButton.setText("Espectador");
        EspectadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspectadorButtonActionPerformed(evt);
            }
        });
        FrameAltaUsuario.getContentPane().add(EspectadorButton);
        EspectadorButton.setBounds(30, 50, 90, 30);

        ArtistaButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ArtistaButton.setText("Artista");
        ArtistaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtistaButtonActionPerformed(evt);
            }
        });
        FrameAltaUsuario.getContentPane().add(ArtistaButton);
        ArtistaButton.setBounds(30, 80, 80, 30);

        LabelNickname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelNickname.setText("Nickname");
        FrameAltaUsuario.getContentPane().add(LabelNickname);
        LabelNickname.setBounds(30, 130, 70, 15);
        FrameAltaUsuario.getContentPane().add(FieldNickname);
        FieldNickname.setBounds(100, 130, 143, 30);

        LabelNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelNombre.setText("Nombre");
        FrameAltaUsuario.getContentPane().add(LabelNombre);
        LabelNombre.setBounds(270, 130, 45, 21);
        FrameAltaUsuario.getContentPane().add(FieldNombre);
        FieldNombre.setBounds(330, 130, 143, 30);

        LabelApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelApellido.setText("Apellido");
        FrameAltaUsuario.getContentPane().add(LabelApellido);
        LabelApellido.setBounds(270, 180, 45, 17);
        FrameAltaUsuario.getContentPane().add(FieldApellido);
        FieldApellido.setBounds(330, 180, 143, 30);

        LabelEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelEmail.setText("Email");
        FrameAltaUsuario.getContentPane().add(LabelEmail);
        LabelEmail.setBounds(30, 180, 45, 17);
        FrameAltaUsuario.getContentPane().add(FieldEmail);
        FieldEmail.setBounds(100, 180, 143, 30);

        LabelFecha_Nac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelFecha_Nac.setText("Fecha nacimiento");
        FrameAltaUsuario.getContentPane().add(LabelFecha_Nac);
        LabelFecha_Nac.setBounds(340, 230, 118, 17);

        LabelDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelDescripcion.setText("Descripcion");
        FrameAltaUsuario.getContentPane().add(LabelDescripcion);
        LabelDescripcion.setBounds(30, 230, 92, 20);
        FrameAltaUsuario.getContentPane().add(FieldDescripcion);
        FieldDescripcion.setBounds(120, 230, 200, 30);

        LabelBiografia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelBiografia.setText("Biografia");
        FrameAltaUsuario.getContentPane().add(LabelBiografia);
        LabelBiografia.setBounds(30, 270, 92, 17);
        FrameAltaUsuario.getContentPane().add(FieldBiografia);
        FieldBiografia.setBounds(120, 270, 200, 30);

        ButtonCancelar.setText("Cancelar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });
        FrameAltaUsuario.getContentPane().add(ButtonCancelar);
        ButtonCancelar.setBounds(270, 390, 90, 30);

        ButtonConfirmar.setText("Confirmar");
        ButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmarActionPerformed(evt);
            }
        });
        FrameAltaUsuario.getContentPane().add(ButtonConfirmar);
        ButtonConfirmar.setBounds(380, 390, 100, 30);

        LabelSitioWeb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelSitioWeb.setText("Link a Sitio Web");
        FrameAltaUsuario.getContentPane().add(LabelSitioWeb);
        LabelSitioWeb.setBounds(30, 310, 92, 17);
        FrameAltaUsuario.getContentPane().add(FieldSitioWeb);
        FieldSitioWeb.setBounds(120, 310, 200, 30);

        ComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ComboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDiaActionPerformed(evt);
            }
        });
        FrameAltaUsuario.getContentPane().add(ComboBoxDia);
        ComboBoxDia.setBounds(410, 250, 70, 30);

        ComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        ComboBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMesActionPerformed(evt);
            }
        });
        FrameAltaUsuario.getContentPane().add(ComboBoxMes);
        ComboBoxMes.setBounds(410, 290, 70, 30);

        ComboBoxAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003" }));
        ComboBoxAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAnioActionPerformed(evt);
            }
        });
        FrameAltaUsuario.getContentPane().add(ComboBoxAnio);
        ComboBoxAnio.setBounds(410, 330, 70, 30);

        LabelDia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelDia.setText("Dia");
        FrameAltaUsuario.getContentPane().add(LabelDia);
        LabelDia.setBounds(340, 250, 60, 20);

        LabelAnio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelAnio.setText("Año");
        FrameAltaUsuario.getContentPane().add(LabelAnio);
        LabelAnio.setBounds(340, 330, 118, 17);

        LabelMes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelMes.setText("Mes");
        FrameAltaUsuario.getContentPane().add(LabelMes);
        LabelMes.setBounds(340, 290, 118, 17);

        FrameConsultarUsuario.setTitle("Consultar informacion de Usuario");
        FrameConsultarUsuario.setVisible(true);
        FrameConsultarUsuario.getContentPane().setLayout(null);

        jScrollPane1.setViewportView(ListaRegistro2);

        FrameConsultarUsuario.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 380, 121, 140);

        LabelNickname2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelNickname2.setText("Nickname");
        FrameConsultarUsuario.getContentPane().add(LabelNickname2);
        LabelNickname2.setBounds(170, 20, 70, 15);

        FieldNickname2.setEditable(false);
        FieldNickname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNickname2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(FieldNickname2);
        FieldNickname2.setBounds(280, 20, 160, 30);

        LabelNombre2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelNombre2.setText("Nombre");
        FrameConsultarUsuario.getContentPane().add(LabelNombre2);
        LabelNombre2.setBounds(170, 60, 70, 15);

        FieldNombre2.setEditable(false);
        FieldNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNombre2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(FieldNombre2);
        FieldNombre2.setBounds(280, 60, 160, 30);

        LabelApellido2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelApellido2.setText("Apellido");
        FrameConsultarUsuario.getContentPane().add(LabelApellido2);
        LabelApellido2.setBounds(170, 100, 70, 15);

        FieldApellido2.setEditable(false);
        FieldApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldApellido2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(FieldApellido2);
        FieldApellido2.setBounds(280, 100, 160, 30);

        LabelCorreo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelCorreo2.setText("Correo");
        FrameConsultarUsuario.getContentPane().add(LabelCorreo2);
        LabelCorreo2.setBounds(170, 140, 70, 15);

        FieldCorreo2.setEditable(false);
        FieldCorreo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldCorreo2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(FieldCorreo2);
        FieldCorreo2.setBounds(280, 140, 160, 30);

        LabelFechaNac2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelFechaNac2.setText("Fecha Nacimiento");
        FrameConsultarUsuario.getContentPane().add(LabelFechaNac2);
        LabelFechaNac2.setBounds(170, 180, 96, 15);

        FieldFechaNac2.setEditable(false);
        FieldFechaNac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldFechaNac2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(FieldFechaNac2);
        FieldFechaNac2.setBounds(280, 180, 160, 30);

        LabelDescripcion2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelDescripcion2.setText("Descripcion");
        FrameConsultarUsuario.getContentPane().add(LabelDescripcion2);
        LabelDescripcion2.setBounds(170, 220, 92, 17);

        FieldDescripcion2.setEditable(false);
        FieldDescripcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldDescripcion2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(FieldDescripcion2);
        FieldDescripcion2.setBounds(280, 220, 160, 30);

        LabelBiografia2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelBiografia2.setText("Biografia");
        FrameConsultarUsuario.getContentPane().add(LabelBiografia2);
        LabelBiografia2.setBounds(170, 260, 92, 17);

        FieldBiografia2.setEditable(false);
        FieldBiografia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldBiografia2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(FieldBiografia2);
        FieldBiografia2.setBounds(280, 260, 160, 30);

        LabelLink2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLink2.setText("Link");
        FrameConsultarUsuario.getContentPane().add(LabelLink2);
        LabelLink2.setBounds(170, 300, 92, 17);

        FieldLink2.setEditable(false);
        FieldLink2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldLink2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(FieldLink2);
        FieldLink2.setBounds(280, 300, 160, 30);

        LabelNickname3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelNickname3.setText("Seleccione un usuario");
        FrameConsultarUsuario.getContentPane().add(LabelNickname3);
        LabelNickname3.setBounds(20, 20, 120, 20);

        LabelEspectaculosOrganizo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelEspectaculosOrganizo2.setText("Espectaculos que organizó");
        FrameConsultarUsuario.getContentPane().add(LabelEspectaculosOrganizo2);
        LabelEspectaculosOrganizo2.setBounds(20, 350, 190, 17);

        ListaUsuarios2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaUsuarios2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaUsuarios2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListaUsuarios2);

        FrameConsultarUsuario.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 50, 130, 280);

        LabelEspectaculosRegistro2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelEspectaculosRegistro2.setText("Funciones de Espectaculos a los que se registró");
        FrameConsultarUsuario.getContentPane().add(LabelEspectaculosRegistro2);
        LabelEspectaculosRegistro2.setBounds(230, 350, 270, 20);

        jScrollPane3.setViewportView(ListaOrganizo2);

        FrameConsultarUsuario.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 380, 121, 140);

        BotonSalir2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        BotonSalir2.setText("Salir");
        BotonSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalir2ActionPerformed(evt);
            }
        });
        FrameConsultarUsuario.getContentPane().add(BotonSalir2);
        BotonSalir2.setBounds(370, 530, 70, 30);

        FrameModificarUsuario.setTitle("Modificar Usuario");
        FrameModificarUsuario.setVisible(true);

        ListaUsuarios3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaUsuarios3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaUsuarios3ValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(ListaUsuarios3);

        LabelSeleccionarUsuario3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelSeleccionarUsuario3.setText("Seleccione un usuario");

        LabelLink3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelLink3.setText("Link");

        LabelApellido3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelApellido3.setText("Apellido");

        LabelFechaNac3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelFechaNac3.setText("Fecha Nacimiento");

        FieldBiografia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldBiografia3ActionPerformed(evt);
            }
        });

        FieldApellido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldApellido3ActionPerformed(evt);
            }
        });

        FieldLink3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldLink3ActionPerformed(evt);
            }
        });

        FieldDescripcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldDescripcion3ActionPerformed(evt);
            }
        });

        LabelDescripcion3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelDescripcion3.setText("Descripcion");

        LabelBiografia3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelBiografia3.setText("Biografia");

        LabelNombre3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelNombre3.setText("Nombre");

        FieldNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNombre3ActionPerformed(evt);
            }
        });

        BotonCancelar3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        BotonCancelar3.setText("Cancelar");
        BotonCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelar3ActionPerformed(evt);
            }
        });

        LabelDia3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelDia3.setText("Dia");

        LabelMes3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelMes3.setText("Mes");

        LabelAnio3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelAnio3.setText("Año");

        ComboBoxDia3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ComboBoxDia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDia3ActionPerformed(evt);
            }
        });

        ComboBoxMes3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        ComboBoxMes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMes3ActionPerformed(evt);
            }
        });

        ComboBoxAnio3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003" }));
        ComboBoxAnio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxAnio3ActionPerformed(evt);
            }
        });

        BotonConfirmar4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        BotonConfirmar4.setText("Confirmar");
        BotonConfirmar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameModificarUsuarioLayout = new javax.swing.GroupLayout(FrameModificarUsuario.getContentPane());
        FrameModificarUsuario.getContentPane().setLayout(FrameModificarUsuarioLayout);
        FrameModificarUsuarioLayout.setHorizontalGroup(
            FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSeleccionarUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                                .addComponent(LabelNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(FieldNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                                .addComponent(LabelApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(FieldApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                                .addComponent(LabelDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FieldDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                                .addComponent(LabelBiografia3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FieldBiografia3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                                .addComponent(LabelLink3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FieldLink3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelFechaNac3)
                            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                                .addComponent(LabelDia3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ComboBoxDia3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelMes3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAnio3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxMes3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxAnio3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                                        .addComponent(BotonCancelar3)
                                        .addGap(18, 18, 18)
                                        .addComponent(BotonConfirmar4)))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        FrameModificarUsuarioLayout.setVerticalGroup(
            FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelSeleccionarUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FrameModificarUsuarioLayout.createSequentialGroup()
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNombre3)
                            .addComponent(FieldNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelApellido3)
                            .addComponent(FieldApellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBiografia3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldBiografia3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLink3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldLink3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LabelFechaNac3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDia3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxDia3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxMes3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelMes3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxAnio3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelAnio3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(FrameModificarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonCancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonConfirmar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );

        jMenuBar1.setName("CoronaTickets"); // NOI18N

        menuUsuario.setText("Usuario");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });

        AltaUsuario.setText("Alta de Usuario");
        AltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(AltaUsuario);

        ConsultaUsuario.setText("Consulta de Usuario ");
        ConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(ConsultaUsuario);

        ModificarUsuario.setText("Modificar Datos de Usuario");
        ModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(ModificarUsuario);

        RegistroFuncionUsuario.setText("Registro a Funcion de Espectaculo");
        RegistroFuncionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroFuncionUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(RegistroFuncionUsuario);

        jMenuBar1.add(menuUsuario);

        menuEspectaculo.setText("Espectaculo");

        AltaEspectaculo.setText("Alta de Espectaculo");
        AltaEspectaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaEspectaculoActionPerformed(evt);
            }
        });
        menuEspectaculo.add(AltaEspectaculo);

        ConsultaEspectaculo.setText("Consulta de Espectaculo");
        ConsultaEspectaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaEspectaculoActionPerformed(evt);
            }
        });
        menuEspectaculo.add(ConsultaEspectaculo);

        jMenuBar1.add(menuEspectaculo);

        menuFuncion.setText("Funcion");

        AltaFuncion.setText("Alta de Funcion de Espectaculo");
        AltaFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaFuncionActionPerformed(evt);
            }
        });
        menuFuncion.add(AltaFuncion);

        ConsultaFuncion.setText("Consulta de Funcion de Espectaculo");
        ConsultaFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaFuncionActionPerformed(evt);
            }
        });
        menuFuncion.add(ConsultaFuncion);

        jMenuBar1.add(menuFuncion);

        menuPaquete.setText("Paquete");

        CrearPaquete.setText("Crear Paquete de Espectaculos");
        CrearPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPaqueteActionPerformed(evt);
            }
        });
        menuPaquete.add(CrearPaquete);

        AgregarEspaPaq.setText("Agregar Espectaculo a Paquete");
        AgregarEspaPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEspaPaqActionPerformed(evt);
            }
        });
        menuPaquete.add(AgregarEspaPaq);

        ConsultaPaquete.setText("Consulta de Paquete de Espectaculo");
        ConsultaPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaPaqueteActionPerformed(evt);
            }
        });
        menuPaquete.add(ConsultaPaquete);

        jMenuBar1.add(menuPaquete);

        menuPlataforma.setText("Plataforma");

        AltaPlataforma.setText("Alta de Plataforma");
        AltaPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaPlataformaActionPerformed(evt);
            }
        });
        menuPlataforma.add(AltaPlataforma);

        jMenuBar1.add(menuPlataforma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(FrameAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(FrameConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FrameModificarUsuario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FrameModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrameConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FrameAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(610, Short.MAX_VALUE))
        );

        try {
            FrameAltaUsuario.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaUsuarioActionPerformed
        // TODO add your handling code here:
        this.FrameAltaUsuario.setSize(673, 500);   
        this.FrameAltaUsuario.setVisible(true);
        this.EspectadorButton.doClick();
        
    }//GEN-LAST:event_AltaUsuarioActionPerformed

    private void ConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuarioActionPerformed
        // TODO add your handling code here:
        this.FrameConsultarUsuario.setVisible(true);
        String lista[] = sis.ColNickname();
        this.ListaUsuarios2.setListData(lista);
    
        
        
        
    }//GEN-LAST:event_ConsultaUsuarioActionPerformed

    private void ModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioActionPerformed
        // TODO add your handling code here:
        this.FrameModificarUsuario.setVisible(true);
        String lista[] = sis.ColNickname();
        this.ListaUsuarios3.setListData(lista);
    }//GEN-LAST:event_ModificarUsuarioActionPerformed

    private void RegistroFuncionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroFuncionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroFuncionUsuarioActionPerformed

    private void AltaEspectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaEspectaculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AltaEspectaculoActionPerformed

    private void ConsultaEspectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaEspectaculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaEspectaculoActionPerformed

    private void AltaFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AltaFuncionActionPerformed

    private void ConsultaFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaFuncionActionPerformed

    private void CrearPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearPaqueteActionPerformed

    private void AgregarEspaPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEspaPaqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarEspaPaqActionPerformed

    private void ConsultaPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaPaqueteActionPerformed

    private void AltaPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaPlataformaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Operación realizada correctamente");
    }//GEN-LAST:event_AltaPlataformaActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void EspectadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspectadorButtonActionPerformed
        // TODO add your handling code here:
        this.FieldDescripcion.disable();
        this.FieldBiografia.disable();
        this.FieldSitioWeb.disable();
        this.FieldDescripcion.setText("");
        this.FieldBiografia.setText("");
        this.FieldSitioWeb.setText("");
    }//GEN-LAST:event_EspectadorButtonActionPerformed

    private void ArtistaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtistaButtonActionPerformed
        // TODO add your handling code here:
        this.FieldBiografia.enable();
        this.FieldDescripcion.enable();
        this.FieldSitioWeb.enable();
  
    }//GEN-LAST:event_ArtistaButtonActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarActionPerformed

        this.FieldNickname.setText("");
        this.FieldNombre.setText("");
        this.FieldApellido.setText("");
        this.FieldEmail.setText("");
        this.FieldBiografia.setText("");
        this.FieldDescripcion.setText("");
        this.FieldSitioWeb.setText("");
        this.ComboBoxDia.setSelectedIndex(0);
        this.ComboBoxMes.setSelectedIndex(0);
        this.ComboBoxAnio.setSelectedIndex(0);
        this.FrameAltaUsuario.setVisible(false);
    }//GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmarActionPerformed
        // TODO add your handling code here:
        
        String email = this.FieldEmail.getText();
        if(sis.UsuarioxEmail(email) == true){ // SE VERIFICA QUE EL EMAIL NO PERTENEZCA A OTRO USUARIO
            JOptionPane.showMessageDialog(this, "ERROR: Ya existe un usuario con ese correo", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
     
        String nickname = this.FieldNickname.getText();
        if(sis.UsuarioxNickname(nickname) == true){ // SE VERIFICA QUE EL NICKNAME NO PERTENEZCA A OTRO USUARIO
            JOptionPane.showMessageDialog(this, "ERROR: Ya existe un usuario con ese nickname", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        String nombre = this.FieldNombre.getText();
        String apellido = this.FieldApellido.getText();
        
        int dia = this.ComboBoxDia.getSelectedIndex() + 1;
        int mes = this.ComboBoxMes.getSelectedIndex() + 1;
        int anio = this.ComboBoxAnio.getSelectedIndex() + 1960;
        
        
        Boolean hayVacios = false;
        
        
        if(nickname.isBlank()|| apellido.isBlank()|| email.isBlank() || nombre.isBlank() ){ hayVacios = true;}
        
        if(hayVacios == true){
            JOptionPane.showMessageDialog(this, "ERROR: Rellene todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
     
        DtFecha f = new DtFecha(dia,mes,anio,0,0,0);
        
        if(this.EspectadorButton.isSelected()){ // SE QUIERE AGREGAR UN ESPECTADOR
            sis.ingresarEspectador(nombre, apellido, email, nickname, f);
            JOptionPane.showMessageDialog(this, "Espectador registrado correctamente", "Registro", JOptionPane.INFORMATION_MESSAGE);
            this.FieldNickname.setText("");
            this.FieldNombre.setText("");
            this.FieldApellido.setText("");
            this.FieldEmail.setText("");
            this.ComboBoxDia.setSelectedIndex(0);
            this.ComboBoxMes.setSelectedIndex(0);
            this.ComboBoxAnio.setSelectedIndex(0);
            this.FrameAltaUsuario.setVisible(false);
            
           
        }
        
        else{ // SE QUIERE AGREGAR UN ARTISTA
            String biografia = this.FieldBiografia.getText();
            String descripcion = this.FieldDescripcion.getText();
            String link = this.FieldSitioWeb.getText();
            
            if(biografia.isBlank() || descripcion.isBlank() || link.isBlank()){ hayVacios = true;}
            
            if(hayVacios){
                JOptionPane.showMessageDialog(this, "ERROR: Rellene todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            sis.ingresarArtista(nombre, apellido, email, nickname, f, biografia, descripcion, link);
            JOptionPane.showMessageDialog(this, "Artista registrado correctamente", "Registro", JOptionPane.INFORMATION_MESSAGE);
            this.FieldNickname.setText("");
            this.FieldNombre.setText("");
            this.FieldApellido.setText("");
            this.FieldEmail.setText("");
            this.FieldBiografia.setText("");
            this.FieldDescripcion.setText("");
            this.FieldSitioWeb.setText("");
            this.ComboBoxDia.setSelectedIndex(0);
            this.ComboBoxMes.setSelectedIndex(0);
            this.ComboBoxAnio.setSelectedIndex(0);
            this.FrameAltaUsuario.setVisible(false);
        }
        // DESPUES DE AGREGAR VOLVER A PONER LOS CAMPOS EN BLANCO  
    }//GEN-LAST:event_ButtonConfirmarActionPerformed

    private void ComboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxDiaActionPerformed

    private void ComboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMesActionPerformed
      
        //SI SELECCIONA FEBRERO 
        if(this.ComboBoxMes.getSelectedItem() == "2" ){
           if(this.ComboBoxDia.getItemCount() == 30){
               this.ComboBoxDia.removeItem("30");
               this.ComboBoxDia.removeItem("29");
           }else if(this.ComboBoxDia.getItemCount() == 31){
               this.ComboBoxDia.removeItem("31");
               this.ComboBoxDia.removeItem("30");
               this.ComboBoxDia.removeItem("29");
           } 
       }
       //SI SELECCIONA UN MES QUE TIENE 30 DIAS
       if(this.ComboBoxMes.getSelectedItem() == "4" ||  this.ComboBoxMes.getSelectedItem() == "6" ||
          this.ComboBoxMes.getSelectedItem() == "9" || this.ComboBoxMes.getSelectedItem() == "11"){

           if(this.ComboBoxDia.getItemCount() == 28){
               this.ComboBoxDia.addItem("29");
               this.ComboBoxDia.addItem("30");
           }else if(this.ComboBoxDia.getItemCount() == 31){
               this.ComboBoxDia.removeItem("31");
           } 
       }

       // SI SELECCIONA UN MES QUE TIENE 31 DIAS
       //Enero, Marzo, Mayo, Julio, Agosto, Octubre y Diciembre.
       if(this.ComboBoxMes.getSelectedItem() == "1" || this.ComboBoxMes.getSelectedItem() == "3" || this.ComboBoxMes.getSelectedItem() == "5" ||
          this.ComboBoxMes.getSelectedItem() == "7" || this.ComboBoxMes.getSelectedItem() == "8" || this.ComboBoxMes.getSelectedItem() == "10" || 
         this.ComboBoxMes.getSelectedItem() == "12"){

           if(this.ComboBoxDia.getItemCount() == 28){
               this.ComboBoxDia.addItem("29");
               this.ComboBoxDia.addItem("30");
               this.ComboBoxDia.addItem("31");
           }else if(this.ComboBoxDia.getItemCount() == 30){
               this.ComboBoxDia.addItem("31");
           } 
       }
    }//GEN-LAST:event_ComboBoxMesActionPerformed

    private void ComboBoxAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAnioActionPerformed

    private void FieldNickname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNickname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNickname2ActionPerformed

    private void FieldNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNombre2ActionPerformed

    private void FieldApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldApellido2ActionPerformed

    private void FieldCorreo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldCorreo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldCorreo2ActionPerformed

    private void FieldFechaNac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldFechaNac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldFechaNac2ActionPerformed

    private void FieldDescripcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldDescripcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldDescripcion2ActionPerformed

    private void FieldBiografia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldBiografia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldBiografia2ActionPerformed

    private void FieldLink2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldLink2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldLink2ActionPerformed

    private void BotonCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelar3ActionPerformed
        // TODO add your handling code here:
        this.FrameModificarUsuario.setVisible(false);
      
        this.FieldNombre3.setText("");
        this.FieldApellido3.setText("");
        this.FieldBiografia3.setText("");
        this.FieldDescripcion3.setText("");
        this.FieldLink3.setText("");
        this.ComboBoxDia3.setSelectedIndex(0);
        this.ComboBoxMes3.setSelectedIndex(0);
        this.ComboBoxAnio3.setSelectedIndex(0);
            
        
    }//GEN-LAST:event_BotonCancelar3ActionPerformed

    private void ListaUsuarios2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaUsuarios2ValueChanged
        // TODO add your handling code here:
        
        this.FieldApellido2.setText("");
        this.FieldNombre2.setText("");
        this.FieldCorreo2.setText("");
        this.FieldNickname2.setText("");
        this.FieldBiografia2.setText("");
        this.FieldDescripcion2.setText("");
        this.FieldLink2.setText("");
        this.FieldFechaNac2.setText("");
        
        String nickname = this.ListaUsuarios2.getSelectedValue();
        nickname = nickname.replace(" (E)", "");
        nickname = nickname.replace(" (A)", "");
        
        DtUsuario dtU = sis.GetDtUsuario(nickname);
        
        String nombre = dtU.GetNombre();
        String apellido = dtU.GetApellido();
        String correo = dtU.GetEmail();
        DtFecha f = dtU.GetFecha_Nac();
        this.FieldNombre2.setText(nombre);
        this.FieldApellido2.setText(apellido);
        this.FieldCorreo2.setText(correo);
        this.FieldNickname2.setText(nickname);
        this.FieldFechaNac2.setText(f.GetFecha());
        
        if(dtU instanceof DtArtista){
            DtArtista dtArt = (DtArtista) dtU;
            
            String biografia = dtArt.GetBiografia();
            String descripcion = dtArt.GetDescripcion();
            String link = dtArt.GetLink();
            
            this.FieldBiografia2.setText(biografia);
            this.FieldDescripcion2.setText(descripcion);
            this.FieldLink2.setText(link);
            
        }
        
        
    }//GEN-LAST:event_ListaUsuarios2ValueChanged

    private void ListaUsuarios3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaUsuarios3ValueChanged
        // TODO add your handling code here:
        this.FieldApellido3.setText("");
        this.FieldNombre3.setText("");
        this.FieldBiografia3.setText("");
        this.FieldDescripcion3.setText("");
        this.FieldLink3.setText("");
        
        String nickname = this.ListaUsuarios3.getSelectedValue();
        nickname = nickname.replace(" (E)", "");
        nickname = nickname.replace(" (A)", "");
        
        DtUsuario dtU = sis.GetDtUsuario(nickname);
        
        String nombre = dtU.GetNombre();
        String apellido = dtU.GetApellido();
        DtFecha f = dtU.GetFecha_Nac();
        
        this.FieldNombre3.setText(nombre);
        this.FieldApellido3.setText(apellido);
        this.ComboBoxDia3.setSelectedIndex(f.GetDia() - 1);
        this.ComboBoxMes3.setSelectedIndex(f.GetMes() - 1);
        this.ComboBoxAnio3.setSelectedIndex(f.GetAnio() - 1960);
        
        
        
        if(dtU instanceof DtArtista){
            DtArtista dtArt = (DtArtista) dtU;
            
            String biografia = dtArt.GetBiografia();
            String descripcion = dtArt.GetDescripcion();
            String link = dtArt.GetLink();
            
            this.FieldBiografia3.setText(biografia);
            this.FieldDescripcion3.setText(descripcion);
            this.FieldLink3.setText(link);
            this.LabelLink3.setVisible(true);
            this.LabelBiografia3.setVisible(true);
            this.LabelDescripcion3.setVisible(true);
            this.FieldBiografia3.setVisible(true);
            this.FieldLink3.setVisible(true);
            this.FieldDescripcion3.setVisible(true);
            
            
        }
        else if(dtU instanceof DtEspectador){
            this.LabelLink3.setVisible(false);
            this.LabelBiografia3.setVisible(false);
            this.LabelDescripcion3.setVisible(false);
            this.FieldBiografia3.setVisible(false);
            this.FieldLink3.setVisible(false);
            this.FieldDescripcion3.setVisible(false);
        }
        
        
    }//GEN-LAST:event_ListaUsuarios3ValueChanged

    private void FieldNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNombre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNombre3ActionPerformed

    private void FieldApellido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldApellido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldApellido3ActionPerformed

    private void FieldDescripcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldDescripcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldDescripcion3ActionPerformed

    private void FieldBiografia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldBiografia3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldBiografia3ActionPerformed

    private void FieldLink3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldLink3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldLink3ActionPerformed

    private void BotonSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalir2ActionPerformed
        // TODO add your handling code here:
        this.FrameConsultarUsuario.setVisible(false);
    }//GEN-LAST:event_BotonSalir2ActionPerformed

    private void ComboBoxDia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDia3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxDia3ActionPerformed

    private void ComboBoxMes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMes3ActionPerformed
        // TODO add your handling code here:
        //SI SELECCIONA FEBRERO 
        if(this.ComboBoxMes3.getSelectedItem() == "2" ){
           if(this.ComboBoxDia3.getItemCount() == 30){
               this.ComboBoxDia3.removeItem("30");
               this.ComboBoxDia3.removeItem("29");
           }else if(this.ComboBoxDia3.getItemCount() == 31){
               this.ComboBoxDia3.removeItem("31");
               this.ComboBoxDia3.removeItem("30");
               this.ComboBoxDia3.removeItem("29");
           } 
       }
       //SI SELECCIONA UN MES QUE TIENE 30 DIAS
       if(this.ComboBoxMes3.getSelectedItem() == "4" ||  this.ComboBoxMes3.getSelectedItem() == "6" ||
          this.ComboBoxMes3.getSelectedItem() == "9" || this.ComboBoxMes3.getSelectedItem() == "11"){

           if(this.ComboBoxDia3.getItemCount() == 28){
               this.ComboBoxDia3.addItem("29");
               this.ComboBoxDia3.addItem("30");
           }else if(this.ComboBoxDia3.getItemCount() == 31){
               this.ComboBoxDia3.removeItem("31");
           } 
       }

       // SI SELECCIONA UN MES QUE TIENE 31 DIAS
       //Enero, Marzo, Mayo, Julio, Agosto, Octubre y Diciembre.
       if(this.ComboBoxMes3.getSelectedItem() == "1" || this.ComboBoxMes3.getSelectedItem() == "3" || this.ComboBoxMes3.getSelectedItem() == "5" ||
          this.ComboBoxMes3.getSelectedItem() == "7" || this.ComboBoxMes3.getSelectedItem() == "8" || this.ComboBoxMes3.getSelectedItem() == "10" || 
         this.ComboBoxMes3.getSelectedItem() == "12"){

           if(this.ComboBoxDia3.getItemCount() == 28){
               this.ComboBoxDia3.addItem("29");
               this.ComboBoxDia3.addItem("30");
               this.ComboBoxDia3.addItem("31");
           }else if(this.ComboBoxDia3.getItemCount() == 30){
               this.ComboBoxDia3.addItem("31");
           } 
       }
        
    }//GEN-LAST:event_ComboBoxMes3ActionPerformed

    private void ComboBoxAnio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxAnio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxAnio3ActionPerformed

    private void BotonConfirmar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonConfirmar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarEspaPaq;
    private javax.swing.JMenuItem AltaEspectaculo;
    private javax.swing.JMenuItem AltaFuncion;
    private javax.swing.JMenuItem AltaPlataforma;
    private javax.swing.JMenuItem AltaUsuario;
    private javax.swing.JRadioButton ArtistaButton;
    private javax.swing.JButton BotonCancelar3;
    private javax.swing.JButton BotonConfirmar4;
    private javax.swing.JButton BotonSalir2;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonConfirmar;
    private javax.swing.JComboBox<String> ComboBoxAnio;
    private javax.swing.JComboBox<String> ComboBoxAnio3;
    private javax.swing.JComboBox<String> ComboBoxDia;
    private javax.swing.JComboBox<String> ComboBoxDia3;
    private javax.swing.JComboBox<String> ComboBoxMes;
    private javax.swing.JComboBox<String> ComboBoxMes3;
    private javax.swing.JMenuItem ConsultaEspectaculo;
    private javax.swing.JMenuItem ConsultaFuncion;
    private javax.swing.JMenuItem ConsultaPaquete;
    private javax.swing.JMenuItem ConsultaUsuario;
    private javax.swing.JMenuItem CrearPaquete;
    private javax.swing.JRadioButton EspectadorButton;
    private javax.swing.JTextField FieldApellido;
    private javax.swing.JTextField FieldApellido2;
    private javax.swing.JTextField FieldApellido3;
    private javax.swing.JTextField FieldBiografia;
    private javax.swing.JTextField FieldBiografia2;
    private javax.swing.JTextField FieldBiografia3;
    private javax.swing.JTextField FieldCorreo2;
    private javax.swing.JTextField FieldDescripcion;
    private javax.swing.JTextField FieldDescripcion2;
    private javax.swing.JTextField FieldDescripcion3;
    private javax.swing.JTextField FieldEmail;
    private javax.swing.JTextField FieldFechaNac2;
    private javax.swing.JTextField FieldLink2;
    private javax.swing.JTextField FieldLink3;
    private javax.swing.JTextField FieldNickname;
    private javax.swing.JTextField FieldNickname2;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTextField FieldNombre2;
    private javax.swing.JTextField FieldNombre3;
    private javax.swing.JTextField FieldSitioWeb;
    private javax.swing.JInternalFrame FrameAltaUsuario;
    private javax.swing.JInternalFrame FrameConsultarUsuario;
    private javax.swing.JInternalFrame FrameModificarUsuario;
    private javax.swing.ButtonGroup GroupTipoUsuario;
    private javax.swing.JLabel LabelAnio;
    private javax.swing.JLabel LabelAnio3;
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelApellido2;
    private javax.swing.JLabel LabelApellido3;
    private javax.swing.JLabel LabelBiografia;
    private javax.swing.JLabel LabelBiografia2;
    private javax.swing.JLabel LabelBiografia3;
    private javax.swing.JLabel LabelCorreo2;
    private javax.swing.JLabel LabelDescripcion;
    private javax.swing.JLabel LabelDescripcion2;
    private javax.swing.JLabel LabelDescripcion3;
    private javax.swing.JLabel LabelDia;
    private javax.swing.JLabel LabelDia3;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEspectaculosOrganizo2;
    private javax.swing.JLabel LabelEspectaculosRegistro2;
    private javax.swing.JLabel LabelFechaNac2;
    private javax.swing.JLabel LabelFechaNac3;
    private javax.swing.JLabel LabelFecha_Nac;
    private javax.swing.JLabel LabelLink2;
    private javax.swing.JLabel LabelLink3;
    private javax.swing.JLabel LabelMes;
    private javax.swing.JLabel LabelMes3;
    private javax.swing.JLabel LabelNickname;
    private javax.swing.JLabel LabelNickname2;
    private javax.swing.JLabel LabelNickname3;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNombre2;
    private javax.swing.JLabel LabelNombre3;
    private javax.swing.JLabel LabelSeleccionarUsuario3;
    private javax.swing.JLabel LabelSitioWeb;
    private javax.swing.JList<String> ListaOrganizo2;
    private javax.swing.JList<String> ListaRegistro2;
    private javax.swing.JList<String> ListaUsuarios2;
    private javax.swing.JList<String> ListaUsuarios3;
    private javax.swing.JMenuItem ModificarUsuario;
    private javax.swing.JMenuItem RegistroFuncionUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenu menuEspectaculo;
    private javax.swing.JMenu menuFuncion;
    private javax.swing.JMenu menuPaquete;
    private javax.swing.JMenu menuPlataforma;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
